services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
  frontend:
    image: nginx:alpine
    ports:
      - "5050:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
